name: bankopol
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  camera: ^0.11.0+2
  collection: ^1.18.0
  cupertino_icons: ^1.0.8
  dart_mappable: ^4.2.2
  dio: ^5.7.0
  flip_card: ^0.7.0
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.5
  google_fonts: ^6.2.1
  google_mlkit_barcode_scanning: ^0.12.1
  hooks_riverpod: ^3.0.0-dev.3
  qr_bar_code_scanner_dialog: ^0.0.5
  riverpod_annotation: ^3.0.0-dev.3
  shared_preferences: ^2.3.2
  uuid: ^4.5.0
  web_socket_channel: ^3.0.1

dev_dependencies:
  build_runner: ^2.4.12
  custom_lint: ^0.5.6
  dart_mappable_builder: ^4.2.3
  flutter_launcher_icons: ^0.14.1
  flutter_test:
    sdk: flutter

  lint: ^2.3.0
  riverpod_generator: ^3.0.0-dev.11
  riverpod_lint: ^3.0.0-dev.4

flutter:
  uses-material-design: true

  assets:
    - assets/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/bankopol_android.png"
  adaptive_icon_background: "#FDFDF1"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/icon/bankopol_web.png"
    background_color: "#FDFDF1"
    theme_color: "#70B57C"
  windows:
    generate: true
    image_path: "assets/icon/bankopol.jpeg"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/icon/bankopol.jpeg"