name: bankopol
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  camera: ^0.11.0+2
  collection: ^1.18.0
  cupertino_icons: ^1.0.8
  dio: ^5.7.0
  flip_card: ^0.7.0
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.5
  google_fonts: ^6.2.1
  google_mlkit_barcode_scanning: ^0.12.0
  hooks_riverpod: ^3.0.0-dev.3
  qr_bar_code_scanner_dialog: ^0.0.5
  riverpod_annotation: ^3.0.0-dev.3
  shared_preferences: ^2.3.2
  uuid: ^4.5.0
  web_socket_channel: ^3.0.1

dev_dependencies:
  build_runner: ^2.4.12
  custom_lint: ^0.5.6
  flutter_test:
    sdk: flutter

  lint: ^2.3.0
  riverpod_generator: ^3.0.0-dev.11
  riverpod_lint: ^3.0.0-dev.4

flutter:
  uses-material-design: true

  assets:
    - assets/