name: Frontend + Backend

on:
  workflow_dispatch: # Manual trigger

jobs:
  frontend:
    uses: ./.github/workflows/publish-frontend.yml
    secrets: inherit

  backend:
    uses: ./.github/workflows/publish-backend.yml
    secrets: inherit
