# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Dart

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true
      - name: Install dependencies
        working-directory: ./frontend
        run: flutter pub get

      - name: Build app
        working-directory: ./frontend
        run: flutter build web --release
      
      - name: Install Netlify
        run: npm install netlify-cli@17.10.1 -g
      
      - name: Deploy to Netlify
        working-directory: ./frontend
        id: netlify_deploy
        run: |
          netlify deploy \
            --dir build/web \
            --site ${{ secrets.NETLIFY_SITE_ID }} \
            --auth ${{ secrets.NETLIFY_API_TOKEN }}
